const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getState: () => ipcRenderer.invoke('get-state'),
  startServer: (siteName) => ipcRenderer.invoke('start-server', siteName),
  stopServer: (siteName) => ipcRenderer.invoke('stop-server', siteName),
  stopAllServers: () => ipcRenderer.invoke('stop-all-servers'),
  openBrowser: (url) => ipcRenderer.invoke('open-browser', url),
  openFolder: (siteName) => ipcRenderer.invoke('open-folder', siteName),
  openSitesFolder: () => ipcRenderer.invoke('open-sites-folder'),
  setPhpPath: () => ipcRenderer.invoke('set-php-path'),
  changeSitesDir: () => ipcRenderer.invoke('change-sites-dir'),
  createSite: (siteName) => ipcRenderer.invoke('create-site', siteName),
  deleteSite: (siteName) => ipcRenderer.invoke('delete-site', siteName),
  toggleAutoStart: (siteName) => ipcRenderer.invoke('toggle-auto-start', siteName),
  debugPhpCheck: () => ipcRenderer.invoke('debug-php-check'),

  startDatabase: (dbType) => ipcRenderer.invoke('start-database', dbType),
  stopDatabase: (dbType) => ipcRenderer.invoke('stop-database', dbType),
  installDatabase: (dbType) => ipcRenderer.invoke('install-database', dbType),
  dbCreateTable: (database, tableName, columns) => ipcRenderer.invoke('db-create-table', database, tableName, columns),
  dbAddColumn: (database, table, column) => ipcRenderer.invoke('db-add-column', database, table, column),
  dbDropColumn: (database, table, columnName) => ipcRenderer.invoke('db-drop-column', database, table, columnName),
  dbInsertRow: (database, table, data) => ipcRenderer.invoke('db-insert-row', database, table, data),
  dbUpdateRow: (database, table, data, where) => ipcRenderer.invoke('db-update-row', database, table, data, where),
  dbDeleteRow: (database, table, where) => ipcRenderer.invoke('db-delete-row', database, table, where),
  dbDropTable: (database, table) => ipcRenderer.invoke('db-drop-table', database, table),
  dbTruncateTable: (database, table) => ipcRenderer.invoke('db-truncate-table', database, table),
  dbResetAutoIncrement: (database, table) => ipcRenderer.invoke('db-reset-auto-increment', database, table),
  dbImportSql: (database, filePath) => ipcRenderer.invoke('db-import-sql', database, filePath),
  dbExportTable: (database, table) => ipcRenderer.invoke('db-export-table', database, table),
  dbExecuteQuery: (query) => ipcRenderer.invoke('db-execute-query', query),
  dbListDatabases: () => ipcRenderer.invoke('db-list-databases'),
  dbCreateDatabase: (name) => ipcRenderer.invoke('db-create-database', name),
  dbDeleteDatabase: (name) => ipcRenderer.invoke('db-delete-database', name),
  dbListTables: (database) => ipcRenderer.invoke('db-list-tables', database),
  dbDescribeTable: (database, table) => ipcRenderer.invoke('db-describe-table', database, table),
  dbGetTableData: (database, table, limit) => ipcRenderer.invoke('db-get-table-data', database, table, limit),

  onAppState: (callback) => ipcRenderer.on('app-state', (_event, data) => callback(data)),
  onServerStarted: (callback) => ipcRenderer.on('server-started', (_event, data) => callback(data)),
  onServerStopped: (callback) => ipcRenderer.on('server-stopped', (_event, data) => callback(data)),
  onServerLog: (callback) => ipcRenderer.on('server-log', (_event, data) => callback(data)),
  onDbStarted: (callback) => ipcRenderer.on('db-started', (_event, data) => callback(data)),
  onDbStopped: (callback) => ipcRenderer.on('db-stopped', (_event, data) => callback(data)),
});
